### ISSUE TITLE
Fusionner embauche.beta.gouv.fr et infrance.org

### ISSUE THREAD

**Issue by laem** [betagouv/syso#273]
Deux _entries_ différentes dans deux index.html différents.

Donc harmoniser le style entre les deux sites, notamment la police.

Idem pour le déploiement, on peut explorer la voie pm2 qui écoute les push github. 

### Todo list avant la fusion avec `master`
- [ ] Unifier le mécanisme de déploiement de infrance et embauche, en changeant la configuration nginx
- [x] Créer deux entrées différentes dans webpack (embauche.gouv.fr et infrance)
- [x] Traduire les textes en français pour embauche
- [ ] Modifier le header pour avoir la progression dans embauche (mais pas les liens vers création d'entreprise et démarche d'embauche)
- [x] Implémenter l'écran de modification des variables
- [x] Implémenter les liens raccourcis en haut de la boite des salaires
- [ ] Intégrer la réstauration de sauvegarde automatique
- [x] Changer l'architecture des dossiers pour avoir les composants du simulateurs au même niveau que ceux de infrance (plusieurs possibilités, à réfléchir)
- [x] Faire en sorte d'avoir un unique dossier `ui` qui comporte tous les composants / styles partagés entre embauche et infrance
- [x] Faire en sorte qu'aucune couleur ne soit codée en dure dans le CSS (utiliser les couleurs du thème uniquement)
- [x] Avoir les liens vers une page résultats depuis la simulation, et un moyen de retourner vers la simulation depuis la vue résultats. 
- [x] Réparer le bouton "retour à la simulation" depuis la page de règle

**Comment by johangirod** [comment]
Proposition de nouvelle architecture dossier
```
- shared/
    - i18n.js
    - utils/
    - ui/
        - buttons/
        - typography.css
        - index.css
    ...
- inFrance.org/
    - components/
    - types/
    - reducer/
    - middlewares/
    - index.html
    - index.js (ou entry.js)

- embauche.gouv.fr/
    - components/
    - index.html
    - index.js (ou entry.js)
    - colour-chooser.html
    - iframe.html
    ...
- simulateur/
    - engine/
        - documentation/
        ...
    - règles/
    - reducers/
    - selectors/
    - index.js
    - types.js
    - routes.js
```
`simulateur/index.js` exporte les reducer, les types et les selecteurs qui peuvent être utiles pour les deux sites.

A partir de là, on pourrait même imaginer publier le simulateur en temps que composant react sur npm, afin que tout le monde puisse en profiter et l'integrer plus en profondeur qu'une iframe.
