### ISSUE TITLE
Mieux que embauche.beta.gouv.fr/simulateur

### ISSUE THREAD

**Issue by laem** [betagouv/syso#72]
Pour que l'offre soit fonctionnellement meilleure que embauche.beta.gouv.fr/simulateur, il reste :

- [x] les problèmes de la saisie du versement transport #67 #71 résolus par #76 :tada: 
- [x]  les associations traité en majeure partie ici #77, la suite dans #78 
- [ ] les subtilités de la taxe sur les salaires #78 
- [x] complémentaire santé #79
- [ ]  le régime Alsace-Moselle #66 
- [x] le temps partiel ici #82

- [x]  le calcul à partir du salaire net

- [x] la vue "bulletin de paie" pour les simulateurs concernés

**Comment by laem** [comment]
Autres choses à vérifier : 
- vérifier que c'est l'assiette cot soc qui est utilisée partout, pas le salaire brut

**Comment by laem** [comment]
Je ferme, on a fait un arbitrage. Les deux sujets Alsace-Moselle et Taxe sur les salaires restent à traiter.
